#!/usr/bin/env python3
"""
Turn the extracted Manager.io JSON into a single SQL file that loads the data
into a Supabase project.

    python3 extract.py "<dir with .manager files>" ./data
    python3 make_seed_sql.py ./data ./seed.sql

Then run seed.sql against the project (Dashboard → SQL Editor, or psql), after
0001_erp_schema.sql has been applied.

Rows are inserted with ON CONFLICT DO UPDATE keyed on the original Manager
GUID, so re-running is safe and idempotent.

Note on balances: imported invoices are marked 'paid' because the Manager books
were not mined for payment/receipt records, so supplier and customer balances
start at zero. Set real opening balances afterwards if you need them.
"""
import sys, os, json


def q(s):
    """Quote a Python value as a SQL literal."""
    if s is None:
        return 'null'
    return "'" + str(s).replace("'", "''") + "'"


def jsonlit(obj):
    return q(json.dumps(obj, ensure_ascii=False, separators=(',', ':'))) + '::jsonb'


def main(src, out_path):
    load = lambda n: json.load(open(os.path.join(src, n)))
    items = load('inventory.json')
    customers = load('customers.json')
    suppliers = load('suppliers.json')
    purchases = load('purchase_invoices.json')
    sales = load('sales_invoices.json')

    by_key = {i['managerKey']: i for i in items}
    supp_by_key = {s['managerKey']: s for s in suppliers}
    cust_by_key = {c['managerKey']: c for c in customers}

    # stable codes for items that had none in Manager
    for n, it in enumerate(sorted(items, key=lambda i: (i['name'].lower(), i['managerKey'])), 1):
        it['_code'] = it.get('code') or f'ITM-{n:04d}'

    out = [
        '-- S.I Trading ERP — Manager.io data import',
        '-- Generated by tools/manager-import/make_seed_sql.py',
        '-- Apply 0001_erp_schema.sql first. Safe to re-run.',
        'begin;',
    ]

    def upsert(table, rid, doc, created=None):
        cols = 'id, doc' + (', "createdAt"' if created else '')
        vals = f'{q(rid)}::uuid, {jsonlit(doc)}' + (f', {q(created)}::timestamptz' if created else '')
        out.append(
            f'insert into {table} ({cols}) values ({vals}) '
            f'on conflict (id) do update set doc = excluded.doc;'
        )

    out.append('\n-- inventory items')
    for it in items:
        upsert('erp_inventory', it['managerKey'], {
            'code': it['_code'], 'name': it['name'] or '(unnamed)',
            'description': '', 'brand': '', 'category': '',
            'unit': it.get('unit') or 'pcs',
            'costPrice': it.get('costPrice') or 0,
            'salePrice': it.get('salePrice') or 0,
            'quantity': it.get('quantity') or 0,
            'reorderLevel': 10, 'warehouseId': '', 'supplierId': '',
            'taxRate': 0, 'barcode': '', 'status': 'active',
            'managerKey': it['managerKey'], 'importedFrom': 'manager.io',
        })

    for label, rows, table, extra in (
        ('customers', customers, 'erp_customers', {'type': 'retail'}),
        ('suppliers', suppliers, 'erp_suppliers', {'category': 'goods'}),
    ):
        out.append(f'\n-- {label}')
        for p in rows:
            upsert(table, p['managerKey'], {
                'name': p['name'] or '(unnamed)', 'company': '', 'email': '',
                'phone': '', 'address': '', 'city': '', 'country': 'Pakistan',
                'balance': 0, 'currency': 'PKR', **extra,
                'managerKey': p['managerKey'], 'importedFrom': 'manager.io',
            })

    def lines(inv):
        built, total = [], 0.0
        for ln in inv.get('lines') or []:
            it = by_key.get(ln.get('itemKey') or '')
            qty = ln.get('qty') or 0
            price = ln.get('unitPrice') or 0
            amount = round(qty * price, 2)
            total += amount
            built.append({
                'itemId': ln.get('itemKey') or '',
                'itemCode': (it or {}).get('_code', ''),
                'itemName': (it or {}).get('name') or ln.get('description') or '(item)',
                'description': ln.get('description') or '',
                'qty': qty, 'unit': (it or {}).get('unit', 'pcs'),
                'unitPrice': price, 'discount': 0, 'taxRate': 0,
                'total': amount, 'isCustom': it is None,
            })
        return built, round(total, 2)

    out.append('\n-- purchase invoices')
    for n, inv in enumerate(sorted(purchases, key=lambda i: (i.get('date') or '', i.get('ref') or '')), 1):
        supp = supp_by_key.get(inv.get('supplierKey') or '')
        items_doc, total = lines(inv)
        upsert('erp_purchase_invoices', inv['managerKey'], {
            'invoiceNo': f'PI-{n:04d}', 'supplierInvoiceNo': inv.get('ref') or '',
            'date': inv.get('date') or '', 'dueDate': '',
            'supplierId': (supp or {}).get('managerKey', ''),
            'supplierName': (supp or {}).get('name', ''),
            'supplierPhone': '', 'supplierAddress': '',
            'status': 'paid', 'paymentMethod': '',
            'notes': f"Imported from Manager.io ({inv.get('book', '')})",
            'items': items_doc, 'subtotal': total, 'discountAmount': 0,
            'taxAmount': 0, 'total': total, 'paidAmount': total, 'currency': 'PKR',
            'managerKey': inv['managerKey'], 'importedFrom': 'manager.io',
        }, inv.get('enteredAt'))

    out.append('\n-- sales invoices')
    for inv in sorted(sales, key=lambda i: (i.get('date') or '', i.get('ref') or '')):
        cust = cust_by_key.get(inv.get('customerKey') or '')
        items_doc, total = lines(inv)
        upsert('erp_sales_invoices', inv['managerKey'], {
            'invoiceNo': inv.get('ref') or '', 'date': inv.get('date') or '', 'dueDate': '',
            'customerId': (cust or {}).get('managerKey', ''),
            'customerName': (cust or {}).get('name', ''),
            'customerPhone': '', 'customerAddress': '',
            'status': 'paid', 'paymentMethod': '',
            'notes': f"Imported from Manager.io ({inv.get('book', '')})",
            'items': items_doc, 'subtotal': total, 'discountAmount': 0,
            'taxAmount': 0, 'total': total, 'paidAmount': total, 'currency': 'PKR',
            'managerKey': inv['managerKey'], 'importedFrom': 'manager.io',
        }, inv.get('enteredAt'))

    out.append('commit;')
    with open(out_path, 'w') as f:
        f.write('\n'.join(out) + '\n')

    print(f'wrote {out_path}')
    print(f'  {len(items)} items, {len(customers)} customers, {len(suppliers)} suppliers,')
    print(f'  {len(purchases)} purchase invoices, {len(sales)} sales invoices')


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
